### ISSUE TITLE
error : sync_woocommerce_resources

### ISSUE THREAD

**Issue by tangymaru** [libracore/WooCommerceConnector#25]
Hi, 

I got below error as below. Could you please guide me how to fix?

`Status
Error
Method
sync_woocommerce_resources
Message
Traceback (most recent call last):
  File "/home/seperp/frappe-bench/apps/woocommerceconnector/woocommerceconnector/api.py", line 43, in sync_woocommerce_resources
    sync_orders()
  File "/home/seperp/frappe-bench/apps/woocommerceconnector/woocommerceconnector/sync_orders.py", line 15, in sync_orders
    sync_woocommerce_orders()
  File "/home/seperp/frappe-bench/apps/woocommerceconnector/woocommerceconnector/sync_orders.py", line 21, in sync_woocommerce_orders
    for woocommerce_order in get_woocommerce_orders():
  File "/home/seperp/frappe-bench/apps/woocommerceconnector/woocommerceconnector/woocommerce_requests.py", line 192, in get_woocommerce_orders
    response = get_request_request('orders?per_page={0}&{1}'.format(_per_page,filter_condition))
  File "/home/seperp/frappe-bench/apps/woocommerceconnector/woocommerceconnector/woocommerce_requests.py", line 48, in get_request_request
    r.raise_for_status()
  File "/home/seperp/frappe-bench/env/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://websiteurl.com/wp-json/wc/v3/orders?per_page=100&after=2020-05-13T11%3A53%3A48.824077%3F&oauth_consumer_key=ck_705d0b564e68165326c87b31fd56XXXXX&oauth_timestamp=1589352027&oauth_nonce=99XXXXXXXXXb23feb500c586c4ebbf3&oauth_signature_method=HMAC-SHA256&oauth_signature=5K2BjaIhTgq%2FOradilbVL1%2Fc%2BylsHHjXIO3DupI1rAE%3D
Request Data
{}`

Installed Apps
ERPNext: v12.8.0 (version-12)

Frappe Framework: v12.3.0 (version-12)

WooCommerce Connector: v1.3.0 (master)

Wordpress and woo commerce both are fresh new installed

**Comment by lasalesi** [comment]
Can you please check if the IDs have been synced? ERPNext needs to have the WooCommerceIDs of the items. This can be done from the button in WooCommerce Configuration...

**Comment by Muzzy73** [comment]
Hi @lasalesi Hope all s good with you. Do you have  Readme/Installation notes for this. We are thinking of having a WooCommerce site linked to ERPNext on V11. Thanks

**Comment by lasalesi** [comment]
There is a new compatibility branch for v11: https://github.com/libracore/WooCommerceConnector/tree/v11
