### ISSUE TITLE
Mapping Woocommerce Tax / Shipping to ERPNext Account

### ISSUE THREAD

**Issue by ardentpros** [libracore/WooCommerceConnector#36]
![WOOCONNECTOR ERROR](https://user-images.githubusercontent.com/68055401/94827497-6a9b3600-0400-11eb-8ef7-430e3b3d342a.JPG)

What are we supposed to do here, I cant save configuration without it and i keep getting error that i should select an ERP Account but i cant select anything in ERPNext Account Text field. When i type it doesn't accept it .

**Comment by lasalesi** [comment]
You need to select a tax account in ERPNext:
![grafik](https://user-images.githubusercontent.com/26505250/94998460-37000d80-05b2-11eb-92ac-c9b4d58ac9c4.png)

If there is no account, you have no tax account. Go to Chart of Accounts and set type of your tax account to Tax:
![grafik](https://user-images.githubusercontent.com/26505250/94998475-526b1880-05b2-11eb-9504-11451540ae4a.png)

**Comment by ardentpros** [comment]
![JSON DECODER ERROR](https://user-images.githubusercontent.com/68055401/95023036-ad644480-0672-11eb-8c2b-2443c1d6fefa.JPG)

Thank you so much for your prompt reply i really appreciate it. I have done as you have said but when i try to save I get the error above. Here is the trace back of the error. 

VM1426:1 POST https://**********.com/api/method/frappe.desk.form.save.savedocs 500 (INTERNAL SERVER ERROR)
(anonymous) @ VM1426:1
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ request.js:220
frappe.call @ request.js:91
c @ save.js:204
frappe.ui.form.save @ save.js:25
(anonymous) @ form.js:626
Promise.then (async)
(anonymous) @ dom.js:265
frappe.run_serially @ dom.js:263
validate_and_save @ form.js:617
(anonymous) @ form.js:557
setTimeout (async)
(anonymous) @ form.js:556
save @ form.js:550
Save @ toolbar.js:450
(anonymous) @ page.js:171
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3
request.js:356 Traceback (most recent call last):
  File "/home/****/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/****/frappe-bench/apps/frappe/frappe/model/document.py", line 281, in save
    return self._save(*args, **kwargs)
  File "/home/***********/frappe-bench/apps/frappe/frappe/model/document.py", line 316, in _save
    self.run_before_save_methods()
  File "/home/***********/frappe-bench/apps/frappe/frappe/model/document.py", line 926, in run_before_save_methods
    self.run_method("validate")
  File "/home/***********/frappe-bench/apps/frappe/frappe/model/document.py", line 827, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/***********/frappe-bench/apps/frappe/frappe/model/document.py", line 1119, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/***********/frappe-bench/apps/frappe/frappe/model/document.py", line 1102, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/***********/frappe-bench/apps/frappe/frappe/model/document.py", line 821, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/***********/frappe-bench/apps/woocommerceconnector/woocommerceconnector/woocommerceconnector/doctype/woocommerce_config/woocommerce_config.py", line 17, in validate
    self.validate_access()
  File "/home/***********/frappe-bench/apps/woocommerceconnector/woocommerceconnector/woocommerceconnector/doctype/woocommerce_config/woocommerce_config.py", line 26, in validate_access
    r = get_request('settings', {"api_key": self.api_key,
  File "/home/***********/frappe-bench/apps/woocommerceconnector/woocommerceconnector/woocommerce_requests.py", line 61, in get_request
    return get_request_request(path, settings).json()
  File "/home/***********/frappe-bench/env/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None


Also can you please help with a detailed guide on how to set this plugin u? A step by step approach and the recommended version of erpnext that it works well with.

**Comment by lasalesi** [comment]
From the trace it seems that you might be missing the api key from your configuration? (value is None and is  required...)
