### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by sptechcue** [libracore/WooCommerceConnector#68]
When I want to install the connector I get the following error message

Getting woocommerceconnector
$ git clone https://github.com/muzzy73/woocommerceconnector.git  --depth 1 --origin upstream
Cloning into 'woocommerceconnector'...
remote: Enumerating objects: 80, done.
remote: Counting objects: 100% (80/80), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 80 (delta 10), reused 45 (delta 4), pack-reused 0
Receiving objects: 100% (80/80), 45.35 KiB | 493.00 KiB/s, done.
Resolving deltas: 100% (10/10), done.
Ignoring dependencies of https://github.com/muzzy73/woocommerceconnector.git. To install dependencies use --resolve-depsInstalling woocommerceconnector
$ /home/bench/frappe/env/bin/python -m pip install --quiet --upgrade -e /home/bench/frappe/apps/woocommerceconnector
$ bench build --app woocommerceconnector
✔ Application Assets Linked

yarn run v1.22.19
$ FRAPPE_ENV=production node rollup/build.js --app woocommerceconnector
Production mode
✔ Built js/moment-bundle.min.js
✔ Built js/libs.min.js
(node:35531) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:1074:7)
    at run_build_command_for_app (/home/bench/frappe/apps/frappe/rollup/build.js:152:27)
    at /home/bench/frappe/apps/frappe/rollup/build.js:49:4
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35531) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35531) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.95s.

**Comment by sptechcue** [comment]
Sol
