### ISSUE TITLE
TypeError: 'InvalidPhoneNumberError' object is not subscriptable

### ISSUE THREAD

**Issue by solaress** [libracore/WooCommerceConnector#75]
I believe this plugin is amazing work, i have successfully imported products and customers but having error on importing orders from woo to erpnext. As i understood some issue with prone numbers, some customers use + or "( )" or space, i believe it causes the error, can you please have a look ? 
Thank you

Traceback (most recent call last):
  File "apps/woocommerceconnector/woocommerceconnector/sync_customers.py", line 153, in create_customer_contact
    }).insert()
  File "apps/frappe/frappe/model/document.py", line 260, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 529, in _validate
    self._validate_data_fields()
  File "apps/frappe/frappe/model/base_document.py", line 859, in _validate_data_fields
    frappe.utils.validate_phone_number(data, throw=True)
  File "apps/frappe/frappe/utils/__init__.py", line 129, in validate_phone_number
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.InvalidPhoneNumberError: '+19567844735 is not a valid Phone Number

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/woocommerceconnector/woocommerceconnector/sync_customers.py", line 60, in create_customer
    create_customer_contact(customer, woocommerce_customer)
  File "apps/woocommerceconnector/woocommerceconnector/sync_customers.py", line 156, in create_customer_contact
    make_woocommerce_log(title=e, status="Error", method="create_customer_contact", message=frappe.get_traceback(),
  File "apps/woocommerceconnector/woocommerceconnector/utils.py", line 54, in make_woocommerce_log
    log.title = title[0:140]
TypeError: 'InvalidPhoneNumberError' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/woocommerceconnector/woocommerceconnector/api.py", line 51, in sync_woocommerce_resources
    sync_customers()
  File "apps/woocommerceconnector/woocommerceconnector/sync_customers.py", line 10, in sync_customers
    sync_woocommerce_customers(woocommerce_customer_list)
  File "apps/woocommerceconnector/woocommerceconnector/sync_customers.py", line 19, in sync_woocommerce_customers
    create_customer(woocommerce_customer, woocommerce_customer_list)
  File "apps/woocommerceconnector/woocommerceconnector/sync_customers.py", line 71, in create_customer
    make_woocommerce_log(title=e, status="Error", method="create_customer", message=frappe.get_traceback(),
  File "apps/woocommerceconnector/woocommerceconnector/utils.py", line 54, in make_woocommerce_log
    log.title = title[0:140]
TypeError: 'TypeError' object is not subscriptable

**Comment by solaress** [comment]
No help here ? 
Plugin doesnt work where the phone number has characters, and if we sync any amazon or ebay data, their phone numbers always contains + at the beginning country code, and "ext" text and xxxx 4 digits in the phone field. 

similar error has been raised and solved on shopify , (https://github.com/frappe/ecommerce_integrations/pull/100/files)   can somebody please help me bypass phone verification on customer createion ?

**Comment by sptechcue** [comment]
How do you have woocommerce data entry configured in woocommerce.

**Comment by solaress** [comment]
> How do you have woocommerce data entry configured in woocommerce.

Data comes to woocommerce from amazon, via wp-lister for amazon plugin to woocommerce( there are other marketplaces to woocommerce plugins as well) , then to erpnext, at least that was the plan, however, as i desperatly need, USA or CA or and soon EU phone numbers are masked by the amazon, so they will always have "ext" text and 4 more digits, so everytime plugin sees a phone number field it throws not a valid phone number. please show us a way not to import this field, or make it as text data readable. thank you

**Comment by sptechcue** [comment]
> phone number field it throws not a valid phone number

I just recreated a purchase in a test system I have using special characters in the phone as you can see, the system imports the data correctly.

<img width="770" alt="3" src="https://github.com/libracore/WooCommerceConnector/assets/110692512/6f6bc675-c27b-448e-8549-b093a6b6ad12">

<img width="778" alt="1" src="https://github.com/libracore/WooCommerceConnector/assets/110692512/6a002514-98b5-4173-ac1b-d1a4464dad1e">

<img width="773" alt="2" src="https://github.com/libracore/WooCommerceConnector/assets/110692512/03686a71-855d-4d99-8d13-396d3a614a48">

<img width="777" alt="4" src="https://github.com/libracore/WooCommerceConnector/assets/110692512/6967c577-0126-4550-8bc9-489e5dafc129">

<img width="784" alt="5" src="https://github.com/libracore/WooCommerceConnector/assets/110692512/1e87363b-ecfd-4fbd-8e72-a30f2cb0e84d">

**Comment by solaress** [comment]
this one seems correct but in my case and on every amazon / ebay phone field the word “ext” or “external” string comes too… can you please try like that ? i know it doesnt make sense to input letters into phone number area, but thats the case and since amazon / ebay does that, it means it will be common use. ( wordpress lets you put text into phone area ) 

in this plugin end maybe a quick fix can be skip confirming the validity of phone, they fixed like that on shopify example.  another approach could send to erp only the numbers and omit the text part. 

thank you for your effort
